# permissions for end users to view devboxrelease1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devbox
    app.kubernetes.io/managed-by: kustomize
  name: devboxrelease1-viewer-role
rules:
- apiGroups:
  - devbox.sealos.io
  resources:
  - devboxrelease1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devbox.sealos.io
  resources:
  - devboxrelease1s/status
  verbs:
  - get
