apiVersion: devbox.sealos.io/v1alpha1
kind: Devbox
metadata:
  labels:
    app.kubernetes.io/name: devbox
    app.kubernetes.io/managed-by: kustomize
  name: devbox-sample
spec:
  state: Running
  resource:
    cpu: 2
    memory: 4Gi
  runtimeRef:
    name: runtime-sample
  network:
    type: NodePort